const TermsConditions = () => {
  return (
    <div className="prose prose-sm sm:prose-base mx-auto py-6">
      <h1 className="text-2xl font-bold text-center mb-6 ">
        Terms and Conditions
      </h1>

      <p className="my-4">
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules thereunder, as applicable, and the
        amended provisions pertaining to electronic records in various statutes
        as amended by the Information Technology Act, 2000. This electronic
        record is generated by a computer system and does not require any
        physical or digital signatures.
      </p>

      <p className="my-4">
        This document is published in accordance with Rule 3(1) of the
        Information Technology (Intermediaries Guidelines) Rules, 2011, which
        require publishing rules, regulations, privacy policy, and Terms of Use
        for access or usage of the domain prodgenie.vercel.app (“Website”),
        including the related mobile site and mobile application (collectively,
        the “Platform”).
      </p>

      <p className="my-4">
        Your use of the Platform and the services offered is governed by these
        Terms and Conditions (“Terms of Use”), including applicable policies
        incorporated herein by reference. By using the Platform, you are
        contracting with the Platform Owner and agree to be bound by these
        Terms.
      </p>

      <h2 className="text-xl font-semibold my-4">Eligibility</h2>

      <p>
        For the purpose of these Terms of Use, “you”, “your”, or “user” shall
        mean any natural or legal person who accesses, browses, or makes use of
        the Platform.
      </p>

      <p className="my-4">
        <strong>
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
          AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
          PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
        </strong>
      </p>

      <p>
        The Platform is owned by Metzap, a company incorporated under the
        Companies Act, 1956, having its registered office at Medavakkam,
        Chennai, India (“Platform Owner”, “we”, “us”, “our”).
      </p>

      <h2 className="text-xl font-semibold my-4">
        The use of the Platform and/or our Services is subject to the following
        Terms of Use:
      </h2>

      <ul className="list-disc ml-6 space-y-4 marker:text-gray-500">
        <li className="pl-2">
          <strong>Payment Instrument:</strong> You agree to provide true,
          accurate, and complete information during and after registration, and
          you shall be responsible for all acts done through your registered
          account.
        </li>

        <li className="pl-2">
          <strong>No Warranties or Guarantees:</strong> Neither we nor any third
          parties provide warranties as to accuracy, timeliness, completeness,
          or suitability of information provided through the Services. You
          acknowledge that such information may contain errors.
        </li>

        <li className="pl-2">
          <strong>User Responsibility:</strong> Your use of the Platform is
          entirely at your own risk. You must independently verify that the
          Services meet your requirements.
        </li>

        <li className="pl-2">
          <strong>Intellectual Property:</strong> All content on the Platform is
          proprietary or licensed. You shall not claim any rights over design,
          layout, graphics, or text.
        </li>

        <li className="pl-2">
          <strong>Unauthorized Use:</strong> Unauthorized use of the Platform
          may result in damages, claims, and legal proceedings.
        </li>

        <li className="pl-2">
          <strong>Charges & Payments:</strong> You agree to pay all charges and
          fees associated with availing the Services.
        </li>

        <li className="pl-2">
          <strong>Prohibited Usage:</strong> You shall not use the Platform for
          unlawful, illegal, harmful, or prohibited purposes.
        </li>

        <li className="pl-2">
          <strong>Third-Party Links:</strong> The Platform may include links to
          third-party sites. Accessing them is subject to their terms and
          policies.
        </li>

        <li className="pl-2">
          <strong>Binding Agreement:</strong> Initiating any transaction forms a
          legally binding contract between you and the Platform Owner.
        </li>

        <li className="pl-2">
          <strong>Indemnification:</strong> You shall indemnify the Platform
          Owner and its affiliates for any claims arising from your breach of
          Terms or violation of applicable laws.
        </li>

        <li className="pl-2">
          <strong>Force Majeure:</strong> Neither party shall be liable for
          performance failures due to events beyond reasonable control.
        </li>

        <li className="pl-2">
          <strong>Governing Law:</strong> These Terms are governed by the laws
          of India.
        </li>

        <li className="pl-2">
          <strong>Jurisdiction:</strong> All disputes shall be subject to the
          exclusive jurisdiction of the courts in Chennai, Tamil Nadu.
        </li>

        <li className="pl-2">
          <strong>Contact & Communication:</strong> All concerns or queries must
          be sent using the contact information provided on the Platform.
        </li>
      </ul>
    </div>
  );
};

export default TermsConditions;
