export { router as authRoutes } from './auth.routes.js';
export { router as fileRoutes } from './file.routes.js';
export { router as userRoutes } from './user.routes.js';
export { router as pdfRoutes } from './pdf.routes.js';
export { router as jobCardRoutes } from './jobCard.routes.js';
export { router as orgRoutes } from './org.routes.js';
export { router as paymentRoutes } from './payment.routes.js';
export { router as thumbnailRoutes } from './thumbnail.routes.js';
export { router as sequenceRoutes } from './sequence.routes.js';
