name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - frontend # Trigger the workflow for the 'frontend' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend with Nx
        run: pnpm nx build frontend

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  deploy:
    needs: build # Ensure deploy runs after build
    runs-on: ubuntu-latest
    env:
      PREVIEW: true
    steps:
      # - name: Deploy to Vercel (via pnpm dlx)
      #   run: pnpm dlx vercel --preview --yes --token=${{ secrets.VERCEL_TOKEN }}

      # Alternatively, if you prefer using `vercel deploy`:
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
