name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend with Nx
        run: pnpm nx build frontend

      # - name: Deploy to Vercel (via pnpm dlx)
      #   run: pnpm dlx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Preview
        run: pnpm dlx vercel deploy --prebuilt --target=preview --token=${{ secrets.VERCEL_TOKEN }}